### ISSUE TITLE
Build with app platform

### ISSUE THREAD

**Issue by amcgee** [dhis2/prop-types#143]
This lib doesn't do any transpiling for `es` builds, which causes a failure in applications which don't use `babel-loader` on `node_modules` (like [maps-app](https://github.com/dhis2/maps-app)).  All of our other frontend libraries apply babel transforms before publishing.  We should align with that standard here, and the best way to do that is to build this lib with the platform instead of a custom build pipeline.

**Comment by varl** [comment]
Moved to: https://jira.dhis2.org/browse/LIBS-1
