### ISSUE TITLE
Re-export react/prop-types as the default export

### ISSUE THREAD

**Issue by varl** [dhis2/prop-types#38]
To use this library we have to do this:

```js
import propTypes from 'prop-types'
import { instanceOfComponent } from '@dhis2/prop-types'
```

We could do what `fs-extra` does, and re-export the original `fs` module together with the additions it makes, so we could do:

```js
import propTypes, { instanceOfComponent } from '@dhis2/prop-types'
```

Where `propTypes` is the default export from `prop-types` as well.

**Comment by Mohammer5** [comment]
Me gusta, I think we'll be doing the same in the `ui-forms` library, re-exporting `Form` and `Field`
