### ISSUE TITLE
Documentation of instanceOfComponent unclear about array of children

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/prop-types#40]
To me the docs are unclear about whether I have to do this:

```js
FooComponent.propTypes = {
    children: propTypes.oneOfType([
        instanceOfComponent(BarComponent),
        propTypes.arrayOf(instanceOfComponent(BarComponent)),
    ]),
}
```

Of if the following will already cover that case:
```js
FooComponent.propTypes = {
    children: instanceOfComponent(BarComponent),
}
```

**Comment by HendrikThePendric** [comment]
I'm not sure I agree with adding specific info about this this to the docs. For prop-types it is pretty much standard that they  operate on singular entities and if you want to allow an array of that entity, you have to wrap it in `propTypes.arrayOf`. I suppose I could add an example...

**Comment by Mohammer5** [comment]
Done through adding examples
